"""
Generator module for Brígh.

Takes the structured output from detectors and writes
context files that AI coding tools can understand.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from brigh import __version__


def generate_context(detections: dict[str, Any]) -> str:
    """
    Build the master .brigh.md content from detection results.
    This is the single source of truth that all other formats derive from.
    """
    sections = []

    # Header.
    sections.append("# Project Context")
    sections.append(f"<!-- Generated by Brígh v{__version__} — https://github.com/404bros/brigh -->")
    sections.append("")

    # Stack overview.
    stack_lines = _build_stack_section(detections)
    if stack_lines:
        sections.append("## Stack")
        sections.extend(stack_lines)
        sections.append("")

    # Architecture and structure.
    structure_lines = _build_structure_section(detections)
    if structure_lines:
        sections.append("## Architecture")
        sections.extend(structure_lines)
        sections.append("")

    # Project map.
    project_map_lines = _build_project_map_section(detections)
    if project_map_lines:
        sections.append("## Project Map")
        sections.extend(project_map_lines)
        sections.append("")

    # Styling.
    styling = detections.get("styling", [])
    if styling:
        sections.append("## Styling")
        for s in styling:
            sections.append(f"- {s}")
        sections.append("")

    # Backend and database.
    backend_lines = _build_backend_section(detections)
    if backend_lines:
        sections.append("## Backend & Data")
        sections.extend(backend_lines)
        sections.append("")

    # Auth.
    auth = detections.get("auth")
    if auth:
        sections.append("## Authentication")
        sections.append(f"- {auth}")
        sections.append("")

    # Testing.
    testing = detections.get("testing", [])
    if testing:
        sections.append("## Testing")
        for t in testing:
            sections.append(f"- {t}")
        sections.append("")
    else:
        sections.append("## Testing")
        sections.append("- No test framework detected")
        sections.append("")

    # Linting and formatting.
    linting = detections.get("linting", [])
    if linting:
        sections.append("## Linting & Formatting")
        for lint in linting:
            sections.append(f"- {lint}")
        sections.append("")

    # Deployment.
    deployment = detections.get("deployment")
    if deployment:
        sections.append("## Deployment")
        sections.append(f"- {deployment}")
        sections.append("")

    # Detection evidence.
    evidence_lines = _build_evidence_section(detections)
    if evidence_lines:
        sections.append("## Detection Evidence")
        sections.extend(evidence_lines)
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def generate_json_payload(detections: dict[str, Any]) -> dict[str, Any]:
    """Build machine-readable scan output."""
    return {
        "schema_version": "1",
        "generated_by": f"brigh/{__version__}",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "detections": detections,
    }


def write_brigh_file(content: str, output_dir: Path) -> Path:
    """Write the master .brigh.md file."""
    path = output_dir / ".brigh.md"
    path.write_text(content, encoding="utf-8")
    return path


def write_claude_file(content: str, output_dir: Path) -> Path:
    """Write CLAUDE.md for Claude Code."""
    path = output_dir / "CLAUDE.md"
    path.write_text(content, encoding="utf-8")
    return path


def write_agents_file(content: str, output_dir: Path) -> Path:
    """Write AGENTS.md for agent-based coding tools."""
    path = output_dir / "AGENTS.md"
    path.write_text(content, encoding="utf-8")
    return path


def write_cursor_file(content: str, output_dir: Path) -> Path:
    """Write .cursorrules for Cursor."""
    path = output_dir / ".cursorrules"
    path.write_text(content, encoding="utf-8")
    return path


def write_copilot_file(content: str, output_dir: Path) -> Path:
    """Write copilot-instructions.md for GitHub Copilot."""
    copilot_dir = output_dir / ".github"
    copilot_dir.mkdir(exist_ok=True)
    path = copilot_dir / "copilot-instructions.md"
    path.write_text(content, encoding="utf-8")
    return path


def write_json_file(payload: dict[str, Any], output_dir: Path) -> Path:
    """Write .brigh.json for machine-readable integrations."""
    path = output_dir / ".brigh.json"
    serialized = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    path.write_text(serialized, encoding="utf-8")
    return path


def write_all(
    content: str,
    output_dir: Path,
    targets: list[str] | None = None,
    json_payload: dict[str, Any] | None = None,
) -> list[Path]:
    """
    Write all requested output files.

    If targets is None, write everything.
    Otherwise only write the specified targets.
    """
    ordered_targets = ["brigh", "claude", "agents", "cursor", "copilot", "json"]
    default_targets = ["brigh", "claude", "agents", "cursor", "copilot"]
    valid_targets = set(ordered_targets)
    if targets is None:
        targets = default_targets.copy()
    else:
        invalid_targets = [target for target in targets if target not in valid_targets]
        if invalid_targets:
            names = ", ".join(sorted(invalid_targets))
            raise ValueError(f"Unknown target(s): {names}")
        # Keep output deterministic and avoid duplicate writes.
        targets = [target for target in ordered_targets if target in set(targets)]

    written = []

    if "brigh" in targets:
        written.append(write_brigh_file(content, output_dir))

    if "claude" in targets:
        written.append(write_claude_file(content, output_dir))

    if "agents" in targets:
        written.append(write_agents_file(content, output_dir))

    if "cursor" in targets:
        written.append(write_cursor_file(content, output_dir))

    if "copilot" in targets:
        written.append(write_copilot_file(content, output_dir))

    if "json" in targets:
        if json_payload is None:
            raise ValueError("JSON target requested but no json_payload was provided")
        written.append(write_json_file(json_payload, output_dir))

    return written


# ── Private helpers ──────────────────────────────────────────────


def _build_stack_section(detections: dict[str, Any]) -> list[str]:
    """Build the stack overview lines."""
    lines = []

    framework = detections.get("framework")
    languages = detections.get("languages", [])
    build_tool = detections.get("build_tool")
    pkg_manager = detections.get("package_manager")

    if framework:
        lang_note = ""
        if "TypeScript" in languages:
            lang_note = " with TypeScript"
        elif "JavaScript" in languages:
            lang_note = " with JavaScript"
        lines.append(f"- {framework}{lang_note}")
    elif languages:
        lines.append(f"- Languages: {', '.join(languages)}")

    if build_tool:
        lines.append(f"- Build tool: {build_tool}")

    if pkg_manager:
        lines.append(f"- Package manager: {pkg_manager}")

    return lines


def _build_structure_section(detections: dict[str, Any]) -> list[str]:
    """Build the architecture/structure lines."""
    lines = []
    structure = detections.get("structure", {})

    source_dir = structure.get("source_dir")
    if source_dir:
        lines.append(f"- Source directory: {source_dir}")

    pattern = structure.get("pattern")
    if pattern:
        lines.append(f"- Structure pattern: {pattern}")

    subdirs = structure.get("src_subdirs", [])
    if subdirs:
        lines.append(f"- Key directories: {', '.join(subdirs)}")

    if structure.get("uses_app_router"):
        lines.append("- Uses App Router (app/ directory)")

    if structure.get("uses_pages_dir"):
        lines.append("- Uses pages/ directory")

    return lines


def _build_backend_section(detections: dict[str, Any]) -> list[str]:
    """Build the backend and database lines."""
    lines = []

    backend = detections.get("backend")
    database = detections.get("database")

    if backend:
        lines.append(f"- Backend/BaaS: {backend}")

    if database:
        lines.append(f"- Database: {database}")

    return lines


def _build_project_map_section(detections: dict[str, Any]) -> list[str]:
    """Build the project map lines."""
    lines: list[str] = []
    project_map = detections.get("project_map", {})

    key_files = project_map.get("key_files", [])
    if key_files:
        lines.append(f"- Key files: {', '.join(key_files)}")

    top_directories = project_map.get("top_directories", [])
    if top_directories:
        lines.append(f"- Top directories: {', '.join(top_directories)}")

    configs = project_map.get("config_files_detected", [])
    if configs:
        lines.append(f"- Configs detected: {', '.join(configs)}")

    commands = project_map.get("suggested_commands", [])
    if commands:
        lines.append("- Suggested commands:")
        for command in commands:
            lines.append(f"  - `{command}`")

    return lines


def _build_evidence_section(detections: dict[str, Any]) -> list[str]:
    """Build concise evidence lines for detected signals."""
    lines: list[str] = []
    evidence = detections.get("evidence", {})
    if not evidence:
        return lines

    order = [
        "languages",
        "framework",
        "build_tool",
        "package_manager",
        "styling",
        "backend",
        "database",
        "auth",
        "testing",
        "linting",
        "deployment",
    ]
    labels = {
        "languages": "Languages",
        "framework": "Framework",
        "build_tool": "Build tool",
        "package_manager": "Package manager",
        "styling": "Styling",
        "backend": "Backend",
        "database": "Database",
        "auth": "Authentication",
        "testing": "Testing",
        "linting": "Linting",
        "deployment": "Deployment",
    }

    for key in order:
        reasons = evidence.get(key, [])
        if not reasons:
            continue
        label = labels.get(key, key)
        for reason in reasons:
            lines.append(f"- {label}: {reason}")

    return lines
